### ISSUE TITLE
do not work

### ISSUE THREAD

**Issue by parsibox** [ammoradi/car-numper-plate-desktop-app#1]
hi
this code only show image in folder and not do any thing
i change this
```
 app.run("Output/plates/" + str(self.i) + "/" + str(self.j) + ".jpg")
```
it do some work and say :
```
   raise child_exception_type(errno_num, err_msg, err_filename)

[ERROR  ] [Image       ] Error reading file Output/plates/1/1.jpg
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
1 10
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 64, in <module>
     simpleApp.run()
   File "/usr/lib64/python3.6/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/usr/lib64/python3.6/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib64/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 746, in mainloop
     self._mainloop()
   File "/usr/lib64/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 478, in _mainloop
     EventLoop.idle()
   File "/usr/lib64/python3.6/site-packages/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/usr/lib64/python3.6/site-packages/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib64/python3.6/site-packages/kivy/base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib64/python3.6/site-packages/kivy/core/window/__init__.py", line 1378, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib64/python3.6/site-packages/kivy/core/window/__init__.py", line 1394, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib64/python3.6/site-packages/kivy/uix/widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib64/python3.6/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "main.py", line 32, in start_callback
     app.run("Output/plates/" + str(self.i) + "/" + str(self.j) + ".jpg")
   File "/home/mohsen/Desktop/python/car-numper-plate-desktop-app/app.py", line 133, in run
     contours = extract_contours(threshold_img)
   File "/home/mohsen/Desktop/python/car-numper-plate-desktop-app/app.py", line 47, in extract_contours
     contours, hierarchy = cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)
 ValueError: too many values to unpack (expected 2)
[mohsen@localhost car-numper-plate-desktop-app]$ 

```

**Comment by parsibox** [comment]
?
